# Generated by Django 3.0 on 2019-12-29 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RdUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=4, unique=True)),
                ('Denom_value', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('total_policy_year', models.PositiveIntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rd_user', to='customers.Customer')),
            ],
            options={
                'ordering': ['serial_no'],
            },
        ),
        migrations.CreateModel(
            name='RdData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kisht_date', models.DateField()),
                ('payment_date', models.DateField()),
                ('message', models.TextField(blank=True, max_length=250, null=True)),
                ('rd_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rd_data', to='rdCustomers.RdUser')),
            ],
        ),
    ]
