# Generated by Django 3.0 on 2020-01-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdCustomers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partial_date_part', models.CharField(choices=[('%Y', 'Year'), ('%Y-%m', 'Month'), ('%Y-%m-%d', 'Day')], max_length=10, verbose_name='Date part')),
                ('partial_date_date', models.DateField()),
                ('some_comment', models.CharField(max_length=100, verbose_name='Comment')),
            ],
        ),
        migrations.AlterModelOptions(
            name='rddata',
            options={'ordering': ['kisht_date'], 'verbose_name': 'rd-data', 'verbose_name_plural': 'RD data'},
        ),
        migrations.AlterField(
            model_name='rddata',
            name='kisht_date',
            field=models.DateField(verbose_name='Kishat Month'),
        ),
        migrations.AlterField(
            model_name='rddata',
            name='message',
            field=models.TextField(blank=True, default='', max_length=250),
        ),
        migrations.AddIndex(
            model_name='rddata',
            index=models.Index(fields=['kisht_date'], name='rdCustomers_kisht_d_f35f81_idx'),
        ),
        migrations.AddConstraint(
            model_name='rddata',
            constraint=models.UniqueConstraint(fields=('rd_user', 'kisht_date'), name='unique kishat'),
        ),
    ]
