# Generated by Django 3.0 on 2020-01-09 11:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rdCustomers', '0003_auto_20200106_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='rddata',
            name='entry_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='rddata',
            name='payment_date',
            field=models.DateField(verbose_name='Payment Received date'),
        ),
        migrations.AlterField(
            model_name='rduser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
